name = "WSTrack"
uuid = "99fc1e6d-1da9-4439-8df4-e3bcd95f41a7"
authors = ["Yi-Kai Kan <tw.ykkan@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
